# Generated by Django 4.1.7 on 2023-02-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0002_alter_todo_description_alter_todo_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.DateField(),
        ),
    ]
