# Generated by Django 4.1.7 on 2023-02-19 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Asosiy', '0004_alter_todo_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Talaba',
        ),
        migrations.AddField(
            model_name='todo',
            name='foydalanuvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Talaba',
        ),
    ]
